BaseURL = "http://blog.gibson.sh"
languageCode = "en-us"
# title = "Daniels Tech Blog"
title = "./gibson.sh --blog"
paginate = 10
theme = "lithium"
pygmentsuseclasses = true
pygmentsstyle = "tango"
PygmentsCodeFences = true
# don't use the chroma highlighting stuff, it makes copying
# from from code blocks with line numbers harder
pygmentsUseClassic = true
relativeURLs = true
disableKinds = ["taxonomy", "taxonomyTerm", "section", "404"]

[params]
  mainSections = ["post"]
  twitterhandle = "@Doomed_Daniel"
  description = "Daniel Gibson's Blog"
  [params.logo]
    url = "logo.png"

[permalinks]
    post = "/:year/:month/:day/:slug"
    page = "/:slug"

[[menu.main]]
    name = "About"
    url = "/about/"

[[menu.main]]
    name = "Github"
    url = "https://github.com/DanielGibson/"

[[menu.main]]
    name = "Mastodon"
    url = "https://mastodon.gamedev.place/@Doomed_Daniel"

[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/Doomed_Daniel"

