BaseURL = "http://blog.gibson.sh"
languageCode = "en-us"
# title = "Daniels Tech Blog"
title = "./gibson.sh --blog"
paginate = 10
theme = "lithium"
relativeURLs = true
disableKinds = ["taxonomy", "taxonomyTerm", "section", "404"]

[markup]
  [markup.highlight]
    #anchorLineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = 'tango'
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 1

  [markup.goldmark.parser]
    autoHeadingID = true
    # defaults to github, but blackfriday is what old hugo used and I want to keep anchor-links compatible
    autoHeadingIDType = 'blackfriday'



[params]
  mainSections = ["post"]
  twitterhandle = "@Doomed_Daniel"
  description = "Daniel Gibson's Blog"
  [params.logo]
    url = "logo.png"

[permalinks]
    post = "/:year/:month/:day/:slug"
    page = "/:slug"

[[menu.main]]
    name = "About"
    url = "/about/"

[[menu.main]]
    name = "Github"
    url = "https://github.com/DanielGibson/"

[[menu.main]]
    name = "Mastodon"
    url = "https://mastodon.gamedev.place/@Doomed_Daniel"

#[[menu.main]]
#    name = "Twitter"
#    url = "https://twitter.com/Doomed_Daniel"

